// ╔══════════════════════════════════════════════════════════════════╗
// ║  ENN EDIT FILE  14  —  FACT OF THE DAY                          ║
// ╠══════════════════════════════════════════════════════════════════╣
// ║  WHAT THIS FILE CONTROLS:                                        ║
// ║    The "Did You Know?" card that appears in the news section      ║
// ║    on the home page. One fact rotates in every night at          ║
// ║    midnight Pacific — cycling through all 365 facts per year.    ║
// ╠══════════════════════════════════════════════════════════════════╣
// ║  HOW TO EDIT:                                                    ║
// ║    Add, remove, or change facts inside the array below.          ║
// ║    Each fact is a string inside quotes, followed by a comma.     ║
// ║    The order doesn't matter — they rotate by day of year.        ║
// ╚══════════════════════════════════════════════════════════════════╝

var ENN_FACTS = [

  // ── JAN 1–31 ────────────────────────────────────────────────────
  "The word 'broadcast' originally meant scattering seeds across a field — radio adapted it to describe signals sent in all directions.",
  "The first radio news broadcast in the U.S. aired on August 31, 1920, on station 8MK in Detroit — now known as WWJ.",
  "KDKA in Pittsburgh was the first commercial radio station in the world. Its very first broadcast covered the 1920 presidential election results.",
  "The teleprompter was invented in 1950. Before it existed, anchors memorized their entire scripts or read directly from paper.",
  "Walter Cronkite was voted 'the most trusted man in America' in a 1972 poll — more trusted than the President at the time.",
  "Walter Cronkite signed off every CBS Evening News broadcast with 'And that's the way it is.'",
  "When Walter Cronkite announced President Kennedy's death on live TV, he removed his glasses, checked the clock, and paused for six silent seconds.",
  "The first live televised presidential debate was Kennedy vs. Nixon on September 26, 1960. Radio listeners thought Nixon won. TV viewers thought Kennedy won.",
  "CNN launched on June 1, 1980 — the world's first 24-hour all-news channel. Critics called it 'Chicken Noodle News' and predicted it would fail.",
  "When CNN launched, founder Ted Turner announced they'd stay on air until the world ended — and kept a special video ready just for that occasion.",
  "The first transatlantic radio broadcast was made by Guglielmo Marconi on December 12, 1901, transmitting a single Morse code letter: S.",
  "Reuters news agency, founded in 1851, originally used carrier pigeons to deliver stock prices between cities before the telegraph arrived.",
  "The term 'scoop' in journalism — breaking a story before competitors — dates to the 1870s, when reporters raced each other to telegraph offices.",
  "The 'inverted pyramid' style of journalism (most important facts first) was developed during the Civil War era, when telegraph lines could cut out mid-transmission.",
  "Barbara Walters became the first woman to solo-anchor a major network evening newscast on ABC in 1976. Her co-anchor publicly said he didn't want a female partner.",
  "B-roll footage — the supplementary cutaway shots you see in news packages — is named after the secondary film reel used in early cinema newsreels.",
  "Newsreels were short news films shown in movie theaters before the main feature. They ran from the 1910s all the way through the 1960s.",
  "The term 'pundit' comes from the Sanskrit word 'pandit,' meaning a learned scholar. It entered English through 19th-century journalism.",
  "'Op-ed' stands for 'opposite the editorial page' — not 'opinion editorial' as most people assume. The New York Times introduced the op-ed page in 1970.",
  "The word 'tabloid' originally meant a condensed news summary, like a tablet of information — only later did it come to mean sensationalized reporting.",
  "Orson Welles' 1938 radio broadcast of 'War of the Worlds' was so realistic because it was formatted as live news bulletins interrupting a music program.",
  "After the War of the Worlds panic, the FCC issued rules about simulating real news broadcasts inside fictional radio programming.",
  "The phrase 'if it bleeds, it leads' summarizes the tendency of local news to prioritize dramatic crime stories — first observed in the 1970s.",
  "Studies show local TV crime coverage has barely changed even as actual crime rates fell dramatically in the 1990s and 2000s.",
  "The first aerial news photograph was taken from a hot air balloon over Boston in 1860 — about 90 years before news helicopters existed.",
  "Photojournalism as we know it was pioneered by Life magazine, which launched in 1936 as a photo-driven news publication.",
  "Margaret Bourke-White was one of the first women photojournalists and the first female war correspondent in World War II.",
  "The first viral news video is often considered the Rodney King beating tape from 1991 — captured by a civilian on a home camcorder.",
  "Twitter's very first breaking news moment was the Hudson River plane landing in 2009 — a photo shared on Twitter reached the world before any news outlet could.",
  "A neighbor live-tweeted the 2011 raid that killed Osama bin Laden without knowing what he was witnessing, breaking the story before any official announcement.",

  // ── FEB 1–28 ────────────────────────────────────────────────────
  "The Challenger disaster in 1986 was witnessed live by millions of schoolchildren — NASA had arranged special classroom broadcasts of the launch.",
  "Over 600 million people watched the Apollo 11 Moon landing live in 1969 — the largest TV audience in history at the time.",
  "The first live satellite news broadcast happened in 1962, when Telstar 1 relayed television signals across the Atlantic Ocean.",
  "The first color TV news broadcast in the U.S. aired on NBC in 1954.",
  "'Breaking news' chyrons — the text banners at the bottom of the screen — are called 'lower thirds' in broadcast terminology.",
  "The ticker text crawling along the bottom of news channels became standard after September 11, 2001, when networks needed to track multiple stories at once.",
  "Before the ticker, that lower-third space was almost never used on news channels. 9/11 changed broadcast design permanently.",
  "The average TV news story runs about 2 minutes and 15 seconds in length.",
  "In the 1950s, a typical nightly news broadcast was only 15 minutes long.",
  "The CBS Evening News expanded from 15 to 30 minutes in 1963 — the very first 30-minute broadcast featured a Cronkite interview with President Kennedy.",
  "Edward R. Murrow's famous sign-off, 'Good night, and good luck,' has been adopted as a phrase of inspiration by journalists for decades.",
  "The first woman to anchor a network evening news broadcast solo was Barbara Walters in 1976. Her co-anchor publicly said he didn't want a female partner.",
  "Peter Jennings dropped out of high school at age 17 but became one of the most respected broadcast journalists in American history.",
  "Dan Rather was famously mugged in 1986 by attackers who kept asking 'What's the frequency, Kenneth?' — the strange incident inspired an R.E.M. song.",
  "R.E.M.'s 1994 hit 'What's the Frequency, Kenneth?' is directly named after Dan Rather's bizarre mugging incident.",
  "Tom Brokaw, Dan Rather, and Peter Jennings all anchored simultaneously in the 1980s–90s — an era considered the golden age of the solo network anchor.",
  "Connie Chung was the first Asian American woman to anchor a major American network newscast.",
  "Diane Sawyer is one of very few journalists to have anchored major primetime newsmagazines at two different Big Three networks.",
  "Geraldo Rivera's 1986 live broadcast opening Al Capone's vault drew 30 million viewers — and the vault was completely empty.",
  "The O.J. Simpson Bronco chase in 1994 was watched live by an estimated 95 million people. NBC split its screen to show both the chase and the NBA Finals.",
  "150 million people watched at least part of the O.J. Simpson verdict — roughly 57% of the entire U.S. population at the time.",
  "Court TV launched in 1991 because televised trials were so popular. It later became truTV.",
  "Cameras are still banned in all federal courtrooms in the U.S. The ban started after the chaos surrounding the 1935 Lindbergh kidnapping trial.",
  "The Lindbergh baby kidnapping trial was the first major 'media circus' of the modern era — and the press behavior was so outrageous that Congress considered regulating it.",
  "Local news is still the most-watched news source in America — more than national network or cable news combined.",
  "The average local TV news broadcast dedicates about 30% of its airtime to weather.",
  "The first TV weather map was hand-drawn on a blackboard — meteorologists used chalk to draw fronts and pressure systems live on air.",
  "Green screen (chroma key) technology was developed in the 1940s for film. Weather forecasters have to train themselves never to wear green on air.",

  // ── MAR 1–31 ────────────────────────────────────────────────────
  "The Weather Channel launched in 1982 and was initially dismissed by cable companies as a terrible idea. Within a year, it was a hit.",
  "Jim Cantore of The Weather Channel is considered a celebrity among storm chasers — locals say if Cantore shows up in your town, it's time to evacuate.",
  "ESPN launched on September 7, 1979 with an audience of only about 30,000 cable subscribers. Its first broadcast was a slow-pitch softball game.",
  "The 'SportsCenter' theme music is one of the most recognized TV jingles in American broadcast history.",
  "The Super Bowl halftime show wasn't always a major spectacle — for the first 20+ years it featured college marching bands and drill teams.",
  "Michael Jackson's 1993 Super Bowl halftime show was so popular it permanently transformed halftime from a halftime activity into a major concert production.",
  "The 'Daily Show with Jon Stewart' is credited with creating an entire genre of fake-news satire that influenced a generation of political media.",
  "Jon Stewart appeared on CNN's 'Crossfire' in 2004, called the hosts 'partisan hacks' on live TV, and the show was cancelled months later.",
  "Stephen Colbert testified before the House Judiciary Committee in 2010 in character as his Colbert Report persona — in front of a live congressional hearing.",
  "After a 'Last Week Tonight' segment on debt buying, John Oliver's team purchased and forgave $15 million in medical debt for 9,000 strangers.",
  "John Oliver's segment on net neutrality generated so many FCC comments that it crashed the FCC's website.",
  "The Onion, America's premier satirical news publication, was founded in 1988 at the University of Wisconsin–Madison as a campus paper.",
  "In 2023, The Onion filed an actual amicus brief in a Supreme Court case defending the legal right to parody — including parody of itself.",
  "SNL's Weekend Update segment has been parodying news since the show's very first episode in 1975. Chevy Chase was the original anchor.",
  "NPR was founded in 1970 and has never carried traditional commercial advertising — funded entirely by member stations and listener donations.",
  "NPR's 'Morning Edition' has been the most-listened-to radio program in America for decades — beating out every commercial station.",
  "About 82% of Americans still listen to AM/FM radio weekly, despite podcasts, streaming, and satellite radio all competing for their ears.",
  "The podcast 'Serial' in 2014 was the fastest podcast to reach 5 million downloads in history — and basically launched the modern podcast era.",
  "The word 'podcast' is a portmanteau of 'iPod' and 'broadcast' — coined around 2004 when the format first emerged.",
  "Over 3 million podcasts exist today — more than 100 times the total number of traditional radio stations in the United States.",
  "Joe Rogan's podcast deal with Spotify was reportedly worth $200 million — the largest single podcast deal in history.",
  "YouTube was founded in 2005. Within a decade it completely changed how people watched and shared news video.",
  "TikTok has become a news source for over 30% of Americans under 30 — a shift that took TV decades longer to achieve.",
  "Instagram was used as a news platform during the 2011 Arab Spring before the app was even one year old.",
  "The first newspaper with a website was the San Jose Mercury News, which launched its online edition in 1993.",
  "The Drudge Report launched in 1996 and broke the Monica Lewinsky story in 1998 — showing for the first time how internet publishing could bypass traditional gatekeepers.",
  "BuzzFeed News won a Pulitzer Prize in 2021, then shut down its entire news division in 2023. Digital media's business model remains deeply unstable.",
  "The newspaper industry's total ad revenue fell from $49 billion in 2005 to under $9 billion by 2018 — largely wiped out by Google and Facebook.",
  "About 2,500 local newspapers have closed in the U.S. since 2005, leaving millions of Americans in 'news deserts' with no local coverage.",
  "News deserts — communities with no local news coverage at all — now affect tens of millions of Americans, mostly in rural areas.",
  "Some local TV stations in small markets have only one or two reporters covering entire counties — sometimes solo anchoring, shooting, and editing their own packages.",

  // ── APR 1–30 ────────────────────────────────────────────────────
  "The Panama Papers (2016) was the largest journalistic collaboration in history — 370+ reporters in 76 countries analyzed 11.5 million leaked documents simultaneously.",
  "Journalists working on the Panama Papers used encrypted apps to communicate secretly for over a year before the story was published.",
  "Data journalism — using spreadsheets, databases, and code to find hidden stories in numbers — became mainstream in newsrooms in the 2010s.",
  "The first major 'computer-assisted reporting' project was by journalist Philip Meyer, who analyzed census data to cover the 1967 Detroit riots.",
  "The New York Times' interactive graphics team has won multiple Pulitzer Prizes — blurring the line between journalism and data visualization.",
  "The Pulitzer Prize, journalism's highest honor, was established in 1917 by newspaper publisher Joseph Pulitzer.",
  "Joseph Pulitzer also co-founded the Columbia School of Journalism — widely considered the most prestigious journalism school in America.",
  "'Yellow journalism' — sensationalized, exaggerated reporting — was named after 'The Yellow Kid,' a comic strip that ran in competing New York newspapers in the 1890s.",
  "William Randolph Hearst and Joseph Pulitzer's 1890s newspaper war was so intense their 'yellow journalism' is partly credited with pushing the U.S. into the Spanish-American War.",
  "The film 'Citizen Kane' (1941) — widely called the greatest movie ever made — is loosely based on William Randolph Hearst.",
  "The Pentagon Papers, leaked in 1971, were published by the New York Times and Washington Post despite direct government attempts to block them.",
  "The Supreme Court ruled 6–3 in favor of publishing the Pentagon Papers, establishing one of the most important First Amendment precedents in history.",
  "Justice Hugo Black wrote in the Pentagon Papers ruling: 'The press was to serve the governed, not the governors.'",
  "Woodward and Bernstein were both in their late 20s when they broke the Watergate story — Bob Woodward was 29, Carl Bernstein was 28.",
  "The Watergate source 'Deep Throat' wasn't publicly revealed until 2005 — 33 years after the story broke. He was W. Mark Felt, the Associate Director of the FBI.",
  "The film 'All the President's Men' (1976) is considered one of the most accurate depictions of real-world journalism ever put on screen.",
  "Wikileaks, founded by Julian Assange in 2006, introduced the concept of anonymous large-scale document leak publishing to the mainstream.",
  "Edward Snowden's 2013 NSA leaks were published by The Guardian and Washington Post — both outlets won Pulitzer Prizes for the coverage.",
  "The Washington Post added the motto 'Democracy Dies in Darkness' to its masthead in 2017.",
  "Jeff Bezos bought the Washington Post in 2013 for $250 million — roughly what Amazon earns in about six hours today.",
  "The New York Times has over 10 million digital subscribers — the largest paid news subscription base in American history.",
  "Deepfake detection is now a growing specialty within newsrooms — journalists have developed entire protocols for verifying whether video footage is real.",
  "The Associated Press began using AI to write financial earnings reports in 2014 — generating about 3,700 stories per quarter automatically.",
  "AI-written news articles have been published by major outlets including USA Today, Bloomberg, and Reuters for routine, data-heavy stories.",
  "The AP serves over 15,000 media organizations in 112 countries with news content every single day.",
  "Reuters transmits over 2 million words of news content per day to subscribers around the world.",
  "AFP (Agence France-Presse), founded in Paris in 1835, is the oldest news agency in the world — a decade older than the AP.",
  "The 'wire' in 'wire service' comes from the telegraph wires that originally delivered news stories — the name stuck long after the technology changed.",
  "United Press International (UPI) had over 2,000 journalists worldwide at its peak in the 1970s. Today it operates with a fraction of that staff.",
  "The phrase 'the media' as a collective noun didn't come into widespread use until the 1960s — before that, people referred to 'the press' or 'the papers.'",

  // ── MAY 1–31 ────────────────────────────────────────────────────
  "The first known act of press censorship occurred in 1501 when Pope Alexander VI issued a papal bull regulating printing presses.",
  "World Press Freedom Day is May 3 — established by the United Nations in 1993 to raise awareness of press freedom around the globe.",
  "Finland consistently ranks as the country with the most press freedom in the world according to Reporters Without Borders.",
  "Finland's high trust in media is partly credited to mandatory media literacy education — Finnish schools teach students to critically evaluate news from an early age.",
  "The U.S. typically ranks around 40th–50th globally in press freedom rankings — lower than most people expect.",
  "Shield laws protect journalists from being forced to reveal confidential sources in court — but not every U.S. state has one.",
  "The First Amendment protects press freedom from government censorship — but it doesn't protect journalists from corporate or advertiser pressure.",
  "Over 2,000 journalists have been killed covering conflicts worldwide since 1992, according to the Committee to Protect Journalists.",
  "Marie Colvin, a war correspondent for the Sunday Times, reported from countless conflict zones wearing a distinctive eye patch. She was killed in Syria in 2012.",
  "Daniel Pearl, a Wall Street Journal reporter, was kidnapped and murdered in Pakistan in 2002 — his death dramatically raised awareness of journalist safety.",
  "Ernie Pyle, WWII's most celebrated war correspondent, traveled directly with troops and wrote humanizing stories about ordinary soldiers. He was killed by machine gun fire weeks before the war ended.",
  "The Committee to Protect Journalists (CPJ) was founded in 1981 to document attacks on press freedom and advocate for imprisoned journalists.",
  "Mexico is one of the deadliest countries in the world for journalists — reporters covering cartel activity face extraordinary risk.",
  "Samizdat — self-published, hand-copied underground news — was how Soviet citizens shared banned information during the Cold War, risking imprisonment to do so.",
  "During the Cold War, Radio Free Europe beamed Western news behind the Iron Curtain. Some listeners risked prison time just to tune in.",
  "Voice of America was launched in 1942. Its very first broadcast stated: 'The news may be good or bad — we will tell you the truth.'",
  "The BBC was founded in 1927 and broadcasts in 42 languages to over 426 million people weekly — one of the world's largest news operations.",
  "Al Jazeera, founded in 1996 in Qatar, was the first pan-Arab news channel and fundamentally changed news access across the Middle East.",
  "The first presidential press conference broadcast live on television was John F. Kennedy's on January 25, 1961. His charisma changed press conference expectations forever.",
  "The FCC requires TV stations to broadcast in the 'public interest, convenience, and necessity' — a rule that has shaped American broadcasting since the Communications Act of 1934.",
  "The Emergency Alert System tone is deliberately designed to be uncomfortable to hear — the specific combination of tones is engineered to be impossible to ignore.",
  "When the national EAS test runs, every TV and radio station in the country is legally required to interrupt programming simultaneously.",
  "The FCC abolished the Fairness Doctrine in 1987, which had required broadcast stations to air balanced viewpoints. Its removal is credited with the rise of partisan talk radio.",
  "Partisan talk radio exploded after the Fairness Doctrine ended in 1987 — Rush Limbaugh launched his national show just one year later.",
  "August is the slowest news month in Washington D.C. — Congress is in recess, the President often vacations, and newsrooms call it the 'August effect.'",
  "The 'August effect' causes a flood of soft, quirky, and unusual human-interest stories to fill airtime during the summer news lull.",
  "Press releases are a major source of news — journalists estimate up to 50% of stories originate from PR submissions rather than original reporting.",
  "Public relations professionals now outnumber journalists in America by roughly 6 to 1, up from about 2 to 1 in the 1980s.",
  "A typical 30-minute local news broadcast contains only about 20 minutes of actual content — the remaining 10 minutes is advertising.",
  "The first TV commercial aired on July 1, 1941, on NBC — a Bulova watch ad that ran for exactly 10 seconds and cost $9.",
  "Super Bowl commercials now cost over $6 million per 30 seconds — making the Super Bowl broadcast the most expensive advertising real estate on television.",

  // ── JUN 1–30 ────────────────────────────────────────────────────
  "The concept of the 'news hole' — the amount of airtime or page space left over after ads — shapes every editorial decision in every newsroom.",
  "Radio's 'golden age' in the 1930s–40s produced original dramas, comedies, and live news programs that families gathered around a single speaker to hear.",
  "The phrase 'glued to the radio' was the 1940s equivalent of doom-scrolling — Americans would listen for hours to live World War II updates.",
  "The first use of the word 'embedded' for journalism was officially introduced by the Pentagon during the 2003 Iraq War — reporters traveled with military units.",
  "Embedded journalism gave reporters unprecedented access to combat but raised serious questions about objectivity when you're eating and sleeping with the soldiers you're covering.",
  "The 60 Minutes stopwatch is one of the most recognized symbols in American television — the show has been on the air since 1968, making it the longest-running primetime news magazine.",
  "Dateline NBC once aired a story with a staged exploding GM truck. The incident led to major overhauls in TV news ethics and standards.",
  "Fox News Channel and MSNBC both launched in 1996 — within two months of each other — in direct response to CNN's 16 years of dominance.",
  "The 'Big Three' broadcast networks (ABC, NBC, CBS) had a combined nightly news audience of around 50 million viewers in the 1970s — a number cable news has never approached.",
  "Local TV newscast ratings during November, February, May, and July are especially important — these are 'sweeps' months that determine advertising prices.",
  "During sweeps, local stations historically aired more sensational stories to boost ratings — a practice journalism ethicists have criticized for decades.",
  "The word 'deadline' in journalism has two competing origin stories: printing press 'dead lines' that type couldn't cross, and Civil War prison camp lines that meant death to cross.",
  "'Lede' — the opening sentence of a news story — is intentionally misspelled to distinguish it from 'lead' type in old printing presses.",
  "'Nut graf' is journalism slang for the paragraph that explains why a story matters to readers — short for 'nutshell paragraph.'",
  "A 'dateline' in journalism is the city and date at the top of a news dispatch — a tradition that dates back to telegraph journalism in the 1800s.",
  "NBC's newsmagazine show 'Dateline' is named directly after this journalism term.",
  "The 'five W's and an H' of journalism — Who, What, When, Where, Why, and How — have been a teaching tool for reporters since the late 1800s.",
  "Newsrooms used to have pneumatic tube systems to shoot printed copy from reporters' desks directly to the editors and printing room floor.",
  "The classic horseshoe-shaped news desk gave us 'rim' editors (the outer ring) and the 'slot' editor (the center) — terms still used today.",
  "The Associated Press Stylebook — the formatting bible of American journalism — has been published annually since 1953.",
  "AP Style says to spell out numbers one through nine and use numerals for 10 and above. Every journalism student memorizes this on day one.",
  "'Thirty' (or the symbol '–30–') was the traditional telegraph signal for the end of a story. Journalists still use it today, even in the digital age. Nobody knows exactly why 30.",
  "The word 'copy' in journalism refers to any written content — as in 'the copy desk,' where editors reviewed all written stories before publication.",
  "'Spin' in political journalism comes from 'spinning a yarn' — crafting a favorable narrative around a news story rather than letting facts speak for themselves.",
  "'Off the record' means a source shares information that can't be published. 'On background' means it can be used but not attributed. 'On the record' means everything is fair game.",
  "The Columbia Scholastic Press Association has been recognizing outstanding student journalism since 1925 — nearly 100 years of celebrating young reporters.",
  "High school journalism students who participate in broadcast programs are measurably more likely to pursue careers in media and communications.",
  "Broadcast journalism programs teach skills that are useful in virtually every career: public speaking, writing under pressure, research, and storytelling.",
  "Some of America's most recognized TV journalists started in high school broadcast programs — including several who went on to major network positions.",
  "Student journalists have broken real local news stories that professional outlets then followed up on — school news is sometimes the only journalism happening in a community.",

  // ── JUL 1–31 ────────────────────────────────────────────────────
  "The Hazelwood v. Kuhlmeier Supreme Court ruling in 1988 allowed school principals to censor student newspapers for 'legitimate pedagogical concerns' — and it's still contested today.",
  "California's Student Free Expression Law gives student journalists more rights than the Hazelwood ruling. Principals there face a much higher legal bar to censor student work.",
  "The Student Press Law Center provides free legal help to student journalists facing censorship — they've defended hundreds of high school and college news outlets.",
  "Award-winning student journalism has exposed real scandals — including investigations that led directly to administrator resignations and policy changes.",
  "The Columbia School of Journalism's Walter Cronkite Award is given annually to broadcast journalism students who best embody Cronkite's values of fairness and accuracy.",
  "News anchors typically train for years to read from a teleprompter while maintaining eye contact, natural expression, and conversational pacing simultaneously.",
  "A professional news anchor can read a full 30-minute broadcast from a teleprompter without missing a beat — even if the copy changes mid-sentence.",
  "The teleprompter reads at 150–180 words per minute — slightly faster than natural conversation but slow enough for clear enunciation.",
  "The average network news anchor earns over $1 million per year. Local anchors in small markets often make under $30,000 — the same as entry-level retail.",
  "Morning news shows like 'Today' and 'Good Morning America' consistently outrate evening newscasts — Americans wake up to news more than they wind down with it.",
  "'Today' on NBC debuted in 1952 — executives initially worried no one would watch TV in the morning. It became the longest-running morning program in U.S. history.",
  "'Good Morning America' debuted in 1975 and didn't surpass 'Today' in ratings until 2012 — after 37 years of playing catch-up.",
  "The GMA studio in Times Square allows crew members to look out the window and see tourists looking in during live national broadcasts.",
  "The 'five-day forecast' on weather broadcasts was only made possible by satellite technology in the 1960s — before that, two or three days was the reliable limit.",
  "Drone journalism became mainstream around 2015 when the FAA loosened commercial drone rules. Drones have changed how news teams cover wildfires, floods, and crowd events.",
  "Before satellite trucks, TV news footage had to be physically rushed to the station — sometimes by motorcycle courier, sometimes by helicopter.",
  "KTLA in Los Angeles pioneered helicopter news coverage in the 1950s and was the first station to broadcast color helicopter footage.",
  "The first use of a helicopter for news gathering happened in Los Angeles in the 1950s — the practice spread nationwide within a decade.",
  "Early TV cameras weighed hundreds of pounds and required full trucks of supporting equipment. Today a smartphone can match their output.",
  "The first smartphone-filmed news story broadcast on a major network aired in 2011 — just four years after the original iPhone launched.",
  "Speed Graphic cameras, used by press photographers from the 1920s through the 1960s, required photographers to carry entire bags of individual flash bulbs — one per shot.",
  "News photographers once had to race to darkrooms to develop film on deadline. Digital cameras didn't become standard in news photography until the mid-1990s.",
  "Reuters became the first major news agency to go fully digital with photography in 1993 — three years before the first consumer digital cameras hit store shelves.",
  "Eddie Adams' 1968 Pulitzer-winning photo of a Viet Cong prisoner being executed at point-blank range contributed to shifting American public opinion against the Vietnam War.",
  "Nick Ut's 1972 'Napalm Girl' photo was nearly not published due to its graphic content — editors decided the news value outweighed the discomfort. It won the Pulitzer.",
  "The concept of 'the decisive moment' — capturing the peak of action in a single frame — was coined by photographer Henri Cartier-Bresson and guides photojournalism to this day.",
  "The term 'media circus' was born covering the 1935 Lindbergh baby kidnapping trial — considered the first true modern spectacle trial.",
  "The National Enquirer broke the story of Gary Hart's extramarital affair in 1987, derailing a frontrunning presidential campaign — one of the few tabloid stories to genuinely reshape political history.",
  "'Tabloid TV' as a genre was pioneered by shows like 'A Current Affair' and 'Hard Copy' in the late 1980s — blurring entertainment and news in ways that still define cable today.",
  "Fox Broadcasting Company launched in 1986, challenging the big three networks for the first time in decades. Most industry insiders predicted it would fail within a year.",
  "America's Most Wanted on Fox (1988) used news-style reporting to help catch real criminals — viewer tips led to over 1,200 fugitive captures during its run.",

  // ── AUG 1–31 ────────────────────────────────────────────────────
  "'Cops' (1989) launched reality TV as we know it, blurring the line between news and entertainment — and ran for an astonishing 32 seasons.",
  "The term 'infotainment' was coined in the 1980s to describe TV programming that blended news content with entertainment production values.",
  "NBC's peacock logo has been the network's symbol since 1956 — originally designed specifically to promote their new color broadcast capabilities.",
  "The first live broadcast of a space shuttle launch was STS-1 in 1981, carried live by all three major broadcast networks.",
  "The Challenger disaster in 1986 happened at 11:39 AM — peak classroom viewing time because NASA had arranged special school broadcasts for the launch.",
  "The STS-51-L Challenger disaster generated some of the most extensive live news coverage in broadcast history, running continuously for days.",
  "The BBC's global news operation broadcasts in 42 languages. Its World Service alone reaches 426 million people weekly across every continent.",
  "The phrase 'media bias' appears in academic literature as early as 1947 — concern about how news organizations frame stories is almost as old as mass media itself.",
  "Nielsen ratings, which measure TV viewership, were introduced in 1950 and still influence every programming and advertising decision in American television.",
  "The first time a newscast beat primetime entertainment programming in ratings was Walter Cronkite's coverage of the Kennedy assassination in November 1963.",
  "ABC, NBC, and CBS all ran continuous commercial-free news coverage for days after 9/11 — an unprecedented move that cost them hundreds of millions in lost ad revenue.",
  "The first 'BREAKING NEWS' graphic on cable TV was introduced by CNN at its launch in 1980. By the 2000s, 'BREAKING' was appearing so often it lost all meaning.",
  "Some news directors now have internal policies limiting 'BREAKING NEWS' banners to stories less than two hours old — trying to restore urgency to the label.",
  "The Nielsen company once estimated that the average American watches roughly 4 hours of television per day — more time than most people spend eating or socializing.",
  "The term 'anchor' for a TV news host was coined by producer Don Hewitt during the 1952 Democratic National Convention to describe Walter Cronkite's central coordinating role.",
  "Don Hewitt later created '60 Minutes' — arguably the most influential TV newsmagazine in history — and ran it for decades.",
  "The first 'investigative journalism' unit at a major U.S. newspaper is widely credited to the Philadelphia Inquirer in the 1960s.",
  "Investigative journalism is the most resource-intensive form of reporting — some investigations take years and cost a single newsroom hundreds of thousands of dollars.",
  "The Internet Archive's Wayback Machine has preserved over 800 billion web pages — including countless news articles that would otherwise have completely disappeared.",
  "The Library of Congress has been preserving newspaper archives since 1897, creating a historical record of American news going back over 200 years.",
  "The New York Times has published every single day since September 18, 1851 — through wars, natural disasters, power outages, and a global pandemic.",
  "The New York Times motto — 'All the News That's Fit to Print' — has appeared on its front page every single day since 1897.",
  "The Reuters Institute at Oxford publishes an annual Digital News Report — the most comprehensive global survey of news consumption habits ever conducted.",
  "According to Reuters Institute surveys, trust in news has been declining in most countries for over a decade. Trust in Finland, however, remains above 60%.",
  "Media literacy education — teaching people to critically evaluate news sources and methods — is widely seen as the most effective tool for combating misinformation.",
  "The first fact-checking organization in America, PolitiFact, launched in 2007. It won the Pulitzer Prize just two years later in 2009.",
  "Snopes, founded in 1994, is the oldest online fact-checking website. It started as a site for debunking folklore and urban legends before moving to news.",
  "Fact-checking as an official journalism role dates back to the 1920s at Time magazine — editors assigned dedicated staff to verify every claim before publication.",
  "The term 'fake news' appeared in actual newspapers as early as 1894 — it described yellow journalism sensationalism, decades before it became a modern political term.",
  "Deepfake videos were first widely detected in 2017, creating a new challenge for news verification that newsrooms are still learning to address.",
  "'The Daily Show' correspondents have included Steve Carell, Ed Helms, Rob Corddry, Samantha Bee, and John Oliver — an alumni list that reads like a comedy hall of fame.",

  // ── SEP 1–30 ────────────────────────────────────────────────────
  "The Watergate scandal that brought down President Nixon was broken by two reporters in their late 20s — proving that age doesn't determine the importance of journalism.",
  "All the major players in the Watergate scandal — including the source 'Deep Throat' — were not revealed publicly for over three decades after the story broke.",
  "The Pentagon Papers leak in 1971 involved 7,000 pages of classified documents — a size so massive that physically copying them was itself a months-long covert operation.",
  "Daniel Ellsberg, who leaked the Pentagon Papers, used a photocopier at night after hours — a one-person operation that changed American history.",
  "The Associated Press has a strict rule against publishing unverified information, even in the age of social media breaking news within seconds.",
  "Reuters explicitly forbids its journalists from taking sides on any issue — a commitment to neutrality that dates back to its 19th-century founding.",
  "The longest-running news program in American television history is 'Meet the Press' on NBC, which debuted in 1947 — over 75 years on air.",
  "The first televised presidential debate (Kennedy-Nixon, 1960) is widely credited with proving that television could decide elections — not just cover them.",
  "Most newsrooms have an 'ethics policy' document outlining rules about conflicts of interest, source protection, correction procedures, and advertiser independence.",
  "Corrections are one of the most important traditions in journalism — running a formal correction when wrong is considered a mark of credibility, not weakness.",
  "'On deep background' is an even stricter version of anonymity than 'on background' — the information can be used only to guide a journalist's understanding, never in print.",
  "The term 'fourth estate' for the press dates to the 18th century, describing the press as an unofficial fourth branch of government alongside the clergy, nobility, and commons.",
  "Edmund Burke is often credited with coining 'fourth estate' in the 1780s, though the exact origin is disputed — the concept stuck regardless.",
  "The Columbia Scholastic Press Association's highest award for high school journalism is named the Gold Crown — fewer than 1% of entries win it each year.",
  "Student journalists in California can publish stories on administrative decisions without prior review under the state's Student Free Expression Law.",
  "The first use of the term 'spin doctor' in print appeared in the New York Times in 1984, describing political advisors managing news narratives after debates.",
  "'Citizen journalism' as a term was first widely used after the 2004 Indian Ocean tsunami, when thousands of amateur videos and photos flooded newsrooms.",
  "The Boston Marathon bombing in 2013 was covered in real time by thousands of eyewitness Twitter accounts — but it also showed how unverified crowdsourced info spreads dangerous misinformation.",
  "During the 2013 Boston bombing investigation, Reddit users wrongly identified innocent people as suspects — a major lesson in the risks of crowdsourced journalism.",
  "The term 'churnalism' — churning out press releases as news without original reporting — was coined by journalist Nick Davies in his book 'Flat Earth News' (2008).",
  "The average online news article now gets 36 seconds of active reading time according to analytics studies — shorter than this fact.",
  "Despite short average reading times, long-form investigative articles regularly outperform short news items in total time spent and shares.",
  "The Pulitzer Prize for Public Service — the most prestigious of all 22 Pulitzer categories — is awarded to the news organization, not an individual journalist.",
  "The first Pulitzer Prizes were awarded in 1917. The original categories were: reporting, editorial writing, history, biography, and novel.",
  "The Pulitzer for photography wasn't added until 1942 — 25 years into the prize's history.",
  "Broadcast journalism Pulitzers weren't added until 2009 — recognizing radio and online audio journalism for the first time.",
  "The Peabody Award, journalism's equivalent of the Oscars for broadcasting, has been awarded annually since 1940.",
  "George Foster Peabody, who funded the award that bears his name, was a banker — not a journalist. He simply believed in the importance of quality broadcasting.",
  "The SPJ (Society of Professional Journalists) publishes an ethics code that thousands of newsrooms use as their foundational guide for reporting decisions.",
  "The SPJ ethics code is built on four principles: seek truth and report it, minimize harm, act independently, and be accountable and transparent.",

  // ── OCT 1–31 ────────────────────────────────────────────────────
  "America's first newspaper, 'Publick Occurrences Both Forreign and Domestick,' was published in Boston in 1690 — and was immediately shut down by the colonial government after one issue.",
  "Benjamin Franklin ran one of colonial America's most successful newspapers, the Pennsylvania Gazette, and pioneered American journalism humor — his paper included satirical letters and commentary.",
  "The world's first newspaper is generally considered to be 'Relation,' published in Strasbourg in 1605 — over 400 years of daily news.",
  "Gutenberg's printing press (c. 1440) made mass media possible — historians consider it the most important technological invention of the second millennium.",
  "The AP was founded in 1846 by a group of New York newspapers that agreed to share the cost of transmitting news from the Mexican-American War by telegraph.",
  "During the Mexican-American War, the AP founders realized that by pooling resources, they could all get faster and more complete news than any single paper could afford alone.",
  "The first recorded news photograph was taken during the Mexican-American War in 1847 — daguerreotypes of battle sites, weeks after the action.",
  "Newsboys — children who sold papers on street corners and shouted headlines — were a defining image of American journalism from the 1830s through the early 1900s.",
  "'Extra! Extra! Read all about it!' was the real cry of newsboys in the 19th and early 20th centuries — screaming headlines to attract buyers in crowded streets.",
  "The Great Chicago Fire of 1871 was covered by reporters who stayed in the burning city as long as possible to file dispatches — risking their lives for the story.",
  "The first undersea telegraph cable connecting America and Europe was laid in 1866 — within days, news that had taken weeks to cross the Atlantic could cross in minutes.",
  "That first transatlantic cable was so revolutionary that it cut news transmission time from 10 days (by ship) to 17 minutes (by telegraph).",
  "The linotype machine, invented in 1886, allowed a single operator to set an entire line of type at once — it made newspapers dramatically faster and cheaper to produce.",
  "Newspapers were so central to American life in the 1800s that most towns had multiple competing dailies — some cities had over a dozen papers.",
  "The New York World and New York Journal sold papers for one or two cents in the 1890s — deliberately cheap to build mass audiences that could sell advertising.",
  "Ida Tarbell's 1904 investigation of Standard Oil, published in McClure's Magazine, is considered one of the greatest pieces of investigative journalism in American history.",
  "Tarbell's investigation helped break up Standard Oil's monopoly — her journalism directly resulted in major legal and policy change.",
  "Upton Sinclair's 1906 novel 'The Jungle' exposed horrific conditions in Chicago meatpacking plants — it led directly to the Pure Food and Drug Act.",
  "Sinclair famously said he 'aimed at the public's heart and by accident hit it in the stomach' — he wanted to expose worker exploitation but instead got food safety reform.",
  "The term 'muckraker' — a journalist who exposes corruption — was used by President Theodore Roosevelt. He meant it as criticism, but journalists embraced it as a badge of honor.",
  "Lincoln Steffens, another muckraker, published 'The Shame of the Cities' in 1904 — exposing corruption in major American municipal governments.",
  "Muckraking journalism of the early 1900s directly contributed to child labor laws, food safety regulations, and antitrust legislation.",
  "The Radio Act of 1927 gave the federal government authority to regulate radio broadcasting — the foundation for all broadcast regulation in America.",
  "The Communications Act of 1934 created the FCC and established the legal framework for all U.S. broadcasting that remains in place today.",
  "The FCC has seven commissioners appointed by the President — no more than four can be from the same political party at any time.",
  "Broadcast TV stations must renew their FCC licenses every eight years. The renewal process includes a public interest review.",
  "The term 'news anchor' stuck because Cronkite 'anchored' the 1952 convention coverage — he was the fixed, stable center while reporters filed from the floor.",
  "Before anchors existed, TV news was read by 'newscasters' — a term that was considered more neutral and less personality-driven than 'anchor.'",
  "The first satellite used exclusively for news was launched by CNN in 1980 — the same year the network launched. It changed everything about how international news was gathered.",
  "Live satellite news feeds are called 'birds' by broadcast technicians — as in 'we've got a bird up' meaning a satellite connection is established.",
  "The standard '5-4-3-2-1 countdown' before a live broadcast comes from early TV — the countdown was originally for analog tape machines to reach stable playback speed.",

  // ── NOV 1–30 ────────────────────────────────────────────────────
  "The term 'media' as a collective noun for news organizations didn't come into widespread use until the 1960s — before that, people just said 'the press.'",
  "The 'press pool' system — where a limited group of journalists represents all media at a restricted event — was formalized during the Nixon administration.",
  "A White House press pool typically consists of one print reporter, one radio reporter, one TV reporter, and one photographer — rotating among outlets.",
  "The White House Correspondents' Association has held its annual dinner since 1921 — but the tradition of roasting the President only became standard in the 1980s.",
  "The White House press briefing room was converted from a swimming pool installed by FDR — reporters literally report over where presidents once swam.",
  "FDR held 998 presidential press conferences during his 12 years in office — more than any other president in history.",
  "FDR's 'fireside chats' on radio — 30 informal addresses between 1933 and 1944 — are credited with rebuilding public confidence during the Great Depression.",
  "FDR's radio strategy was so effective that historians credit it with saving American democracy during its most vulnerable period. He understood the medium.",
  "JFK was the first president to use television as his primary communication tool — and his comfort in front of cameras gave him a decisive political advantage.",
  "Ronald Reagan's background as a Hollywood actor and radio broadcaster made him one of the most media-savvy presidents in American history. He was called 'The Great Communicator.'",
  "The term 'news cycle' originally referred to the 24-hour rhythm of morning and evening newspapers. Today it can mean a cycle of minutes on social media.",
  "The '24-hour news cycle' created by CNN in 1980 is now considered slow — Twitter and social media have created an effectively real-time news cycle.",
  "The phrase 'media echo chamber' describes how people who only consume news that confirms their existing beliefs become increasingly isolated from other viewpoints.",
  "Studies on media echo chambers suggest that social media algorithms actively contribute to political polarization by showing users content they're likely to agree with.",
  "The Reuters Institute found in 2023 that 36% of people surveyed actively try to avoid the news — up significantly from just a decade ago.",
  "Despite news avoidance trends, interest in local news actually increased during the COVID-19 pandemic — people wanted information about their immediate communities.",
  "COVID-19 generated more consecutive days of major news coverage than any event since World War II — news organizations ran 24/7 for months.",
  "The term 'infodemic' was coined during the COVID-19 pandemic to describe the overwhelming flood of both accurate and false information circulating simultaneously.",
  "Wikipedia, launched in 2001, is now cited by millions of people as a news reference — though journalists are typically forbidden from citing it directly.",
  "Wikipedia's news reliability varies by topic — studies show politically charged articles are edited far more frequently than scientific or historical ones.",
  "The first use of Twitter for news was widely considered to be the 2007 Loma Prieta earthquake response — but the platform became truly newsworthy during the 2009 Iranian election protests.",
  "During the 2009 Iranian election protests, Twitter users changed their profile locations to Tehran to confuse government tracking — a rare case of social media users defending journalists.",
  "The Arab Spring protests of 2010–2012 were heavily documented on Facebook, Twitter, and YouTube — earning social media the label of 'liberation technology.'",
  "Subsequent research cast doubt on whether social media actually caused the Arab Spring or simply documented it — a debate that continues in media studies today.",
  "The Gutenberg Bible (c. 1455) was one of the first books printed with movable type — and within decades, printing spread news, ideas, and eventually revolution across Europe.",
  "Martin Luther's 95 Theses in 1517 spread rapidly because of the printing press — historians call it the first 'viral' information event in modern history.",
  "It took the printing press 50 years to spread widely across Europe. The internet spread globally in less than 10 years. Social media took less than 5.",
  "The first 'op-ed' page in American newspaper history was introduced by the New York Times on September 21, 1970 — specifically to give voices outside the newsroom a platform.",
  "Opinion journalism and straight news have been separated by ethical rules since the early 20th century — the 'firewall' between news and opinion is foundational to credibility.",
  "The Columbia Journalism Review, founded in 1961, is journalism's primary watchdog publication — it critiques media coverage and holds news organizations accountable.",

  // ── DEC 1–31 ────────────────────────────────────────────────────
  "The first use of 'scoop' as a verb — 'to scoop a competitor' — appeared in print in the Chicago Tribune in 1874.",
  "Wire service reporters in the 1940s used to physically punch tape to transmit stories. A fast tape-puncher was a valued newsroom skill.",
  "The Teletype machines that clattered in newsrooms 24/7 until the 1980s were so integral to news culture that their sound appeared in countless TV show opening sequences.",
  "The CBS News 'Special Report' music — that distinctive breaking news theme — was composed in 1967 and is still used today.",
  "NBC's 'ding-ding-ding-ding' breaking news chime is one of the most recognized sounds in American broadcasting — it's been the same since the 1970s.",
  "The ABC News 'stinger' — its short, sharp breaking news fanfare — was composed by Ron Jones and has been used since 1968.",
  "NPR's distinctive hour-by-hour timekeeping tones are called 'pips' — they're based on a similar system used by the BBC since 1924.",
  "The BBC's famous hourly time signal, known as the 'pips,' was introduced in 1924 — exactly six short tones followed by a long tone on the hour.",
  "CBS's 'tick-tick-tick' stopwatch sound that opens '60 Minutes' has been running since 1968 — it's the longest-running audio brand in American TV news.",
  "The first live TV broadcast of a presidential inauguration was Dwight D. Eisenhower's on January 20, 1953.",
  "Every U.S. presidential inauguration since Eisenhower's has been broadcast live on national television — a tradition of transparent democratic transfer of power.",
  "The Zapruder film — an amateur 8mm movie of the Kennedy assassination — is one of the most analyzed pieces of footage in history and was purchased by Time magazine for $150,000 in 1963.",
  "Abraham Zapruder was a Dallas dressmaker who had brought his camera to Dealey Plaza specifically to film the presidential motorcade. He had no idea what he was about to capture.",
  "Satellites have made it possible for a single news organization to broadcast live from virtually anywhere on Earth — a capability that was science fiction just 70 years ago.",
  "The phrase 'on the ground reporting' distinguishes journalists who are physically present at a story from those analyzing it from a studio — a distinction viewers trust enormously.",
  "International news bureaus — permanent offices with staff journalists based abroad — were pioneered by the Associated Press in the 1860s and remain essential to global coverage.",
  "The Washington Post's famous 'Deep Throat' source met Bob Woodward in underground parking garages — Woodward signaled meetings needed using a flower pot on his balcony.",
  "Nixon's press secretary Ron Ziegler said the Watergate break-in was a 'third-rate burglary attempt' — the dismissive quote became famous as the cover-up unraveled.",
  "The phrase 'the truth will out' is Shakespeare's — but journalism is how it usually happens.",
  "Rupert Murdoch's News Corp owns media properties on three continents — including Fox News, the Wall Street Journal, and newspapers across the U.S., UK, and Australia.",
  "The news industry is currently in its greatest period of transformation since Gutenberg — experts call it the 'fourth media revolution,' after printing, broadcasting, and cable.",
  "AI is already writing financial news, weather summaries, and sports recaps at major outlets. The question isn't whether AI will change journalism — it already has.",
  "The core job of a journalist has been exactly the same for 400 years: find out what is happening, verify it, and tell people the truth about it.",
  "The first student-run newspaper in America was 'The Students' Gazette' at William and Mary College in 1736 — student journalism is almost as old as America itself.",
  "High school newspapers have published investigative stories that led to real-world changes — including exposing school budget fraud and safety violations.",
  "A well-run school broadcast program produces journalists, public speakers, editors, producers, and critical thinkers — skills that last well beyond any single story.",
  "In communities where professional newsrooms have shut down, student journalists are sometimes the only reporters left covering local school board meetings, elections, and events.",
  "Every major story you've ever seen — the Moon landing, 9/11, a local championship game — was covered by someone who started exactly where student journalists start: curious, a camera, and a deadline.",
  "The best journalists in history share one trait: they cared more about getting the story right than getting it first. Accuracy over speed. Every time.",
  "ENN has been on the air at Eastlake High School, broadcasting live Monday through Thursday to the student body. That's real journalism — and it matters.",
  "You're watching student-produced journalism. The anchors, reporters, and producers on ENN are your classmates — and they're telling your school's story, every single day.",

];
