// ╔══════════════════════════════════════════════════════════════════╗
// ║  ENN EDIT FILE  15  —  BROADCAST BINGO                          ║
// ╠══════════════════════════════════════════════════════════════════╣
// ║  WHAT THIS FILE CONTROLS:                                        ║
// ║    The Broadcast Bingo card in The Bullpen section.              ║
// ║    • 300 squares the card draws from                             ║
// ║    • Card auto-refreshes every Monday at midnight PT             ║
// ║    • All students get the same card each week                    ║
// ╠══════════════════════════════════════════════════════════════════╣
// ║  HOW TO EDIT:                                                    ║
// ║    Add, remove, or rewrite squares in the array below.           ║
// ║    Each square is a string in quotes, followed by a comma.       ║
// ║    Keep them short — they have to fit in a small grid cell.      ║
// ╚══════════════════════════════════════════════════════════════════╝

var ENN_BINGO = {

  /* ✏️ EDIT: Bingo card title and section copy */
  heading:  'BROADCAST BINGO',
  subhead:  'Same card for every student. Refreshes every Monday.',
  bingoMsg: 'BINGO',

  /* ✏️ BINGO SQUARES — edit or add here ─────────────────────────
     300 squares drawn from 6 categories:
       Anchor Behavior · Script & Copy · Technical Issues
       Content & Topics · Eastlake Specific · Meta
     Add new squares at the end of the list — the card randomly
     picks 16 each week using the week number as a seed.          */

  squares: [

    // ── ANCHOR BEHAVIOR (50) ──────────────────────────────────────
    'Anchor mispronounces a word',
    'Anchor shuffles papers at the end',
    'Anchor looks slightly off-camera',
    'Anchor smiles mid-sentence',
    'Anchor says "and finally…"',
    'Anchor blinks rapidly during a tense moment',
    'Anchor nods while intro reads',
    'Anchor adjusts collar on camera',
    'Anchor says "back to you" to no one',
    'Anchor pauses longer than expected',
    'Anchor laughs off-script',
    'Anchor clears throat before a story',
    'Anchor says "as you may know"',
    'Anchor reads from wrong camera',
    'Anchor says "and in other news"',
    'Anchor reads from paper not teleprompter',
    'Anchor tilts head dramatically',
    'Anchor uses a student name too formally',
    'Both anchors speak at the same time',
    'Anchor skips the pause between stories',
    'Anchor says "moving on" 3+ times',
    "Anchor's voice cracks mid-sentence",
    'Anchor gestures while sitting at the desk',
    'Anchor uses air quotes',
    'Anchor says "literally" on air',
    'Anchor introduces the wrong reporter',
    'Anchor stumbles on the same word twice',
    "Anchor's mic pops on a B or P",
    'Anchor glances down before a transition',
    'Anchor exhales audibly before starting',
    'Anchor says "um" or "uh" on air',
    'Anchor does a double-take at camera',
    'Anchor leans too close to the mic',
    'Anchor self-corrects a date',
    'Anchor says "let\'s take a look"',
    "Anchor's name chyron has a typo",
    'Anchor says "thank you" to the camera',
    'Anchor waves goodbye at the close',
    'Anchor forgets to smile at sign-off',
    'Anchor visibly flips to a new script page',
    'Anchor says "very special story"',
    'Anchor uses "exciting" twice',
    "Anchor can't say a teacher's last name",
    "Anchor can't say a student's first name",
    'Anchor says "we\'ll be right back"',
    'Anchor wears school colors',
    "Anchor's earpiece is visible",
    'Anchor says "I" instead of "we"',
    'Anchor reads a story too fast',
    'Anchor over-enunciates every word',

    // ── SCRIPT & COPY (50) ───────────────────────────────────────
    'A story runs over 90 seconds',
    'A story has zero B-roll — just talking heads',
    'Reporter forgets to say their name in standup',
    'Lower-third has a grammatical error',
    'Reporter stumbles on a statistic',
    'Intro and reporter say the exact same thing',
    'A story ends with no sign-off',
    'Reporter says "uh" from the script',
    'A celebrity name is in a story',
    '"According to officials" is used',
    'A story runs under 30 seconds',
    'A teased story never airs',
    'Wrong tense used in a story',
    'A story teased early doesn\'t appear until the end',
    "Story headline doesn't match the content",
    'Reporter uses "just" three times in one sentence',
    'A number in a story is clearly wrong',
    'Reporter improvises around teleprompter lag',
    '"Students say" but no student is quoted',
    'A quote is attributed to the wrong person',
    '"Breaking" used for last week\'s news',
    'Reporter misidentifies a campus building',
    '"Exciting" appears in a story script',
    '"At this point in time" used instead of "now"',
    'A story transition makes no sense',
    'Reporter repeats the same point twice',
    'A story ends with "only time will tell"',
    '"We reached out and did not hear back"',
    'Broadcast ends before the rundown is finished',
    '"Utilize" when they mean "use"',
    'A date with no day of the week',
    'Background music doesn\'t fit the story',
    'A quote is clearly paraphrased, not a soundbite',
    '"This just in" about something days old',
    'Two consecutive stories are completely unrelated',
    'B-roll doesn\'t match what\'s being said',
    '"Very unique" is used',
    'A story graphic uses clip art',
    'A student\'s grade level is wrong',
    'A story uses future tense for a past event',
    'Homework or tests are mentioned',
    'A story begins with "and so"',
    'A sports story doesn\'t include the final score',
    'Reporter says "moving on" to escape a stumble',
    'A story opens with a rhetorical question',
    'A tease recycles a story from a previous day',
    '"At the end of the day" is used',
    '"More on this as it develops" — but it\'s resolved',
    '"Community" used four or more times in one story',
    'A club event has no date or location',

    // ── TECHNICAL ISSUES (50) ────────────────────────────────────
    'Lower-third chyron has a typo',
    'Audio dips suddenly for a second',
    'Two people accidentally talk at once',
    'A graphic shows up a full beat late',
    'The wrong graphic stays on screen too long',
    'Background music plays when it shouldn\'t',
    'A video clip plays without any audio',
    'Wrong B-roll plays over a story',
    'Broadcast starts more than 30 seconds late',
    'Live shot has a noticeable echo',
    'A chyron disappears before you finish reading it',
    'A graphic appears before it\'s introduced',
    'Camera is visibly shaky in a standup',
    'Reporter is backlit and hard to see',
    'Reporter is in a distractingly loud location',
    'A microphone is clearly visible in frame',
    'Broadcast cuts to black for a moment',
    'A title card stays on screen a beat too long',
    'Audio is noticeably louder in one segment',
    'Video stutters or freezes for a moment',
    'Lower-third appears on the wrong person',
    'A story package plays out of order',
    'The anchor\'s name is missing from the chyron',
    'A sound effect plays at the wrong moment',
    'The intro bumper loops or stutters',
    'End credits roll over an unfinished story',
    'Camera accidentally zooms in',
    'Broadcast ends without a formal close',
    'Lavalier mic rustles against clothing',
    'The draft version of a graphic airs',
    'Reporter\'s background has a distracting object',
    'Camera white balance is clearly off',
    'A chyron covers someone\'s face',
    'Anchor\'s chyron appears during reporter\'s story',
    'A graphic blocks the visual content',
    'Reporter\'s standup location doesn\'t match the story',
    'A reaction shot is used in the wrong context',
    'Broadcast transitions with a sound effect',
    'A clip has visible timecode in the corner',
    'Reporter appears to read off their phone',
    'Closing music is louder than the anchor\'s voice',
    'A camera operator\'s arm is briefly in frame',
    'Graphics use a completely different color scheme',
    'The broadcast clock freezes or jumps',
    'The anchor\'s chair squeaks audibly',
    'An animation looks off-brand',
    'Reporter finishes but their feed keeps going silently',
    'A lower-third text runs off the screen edge',
    'Broadcast cuts to a story before the anchor intro',
    'A freeze-frame is used as if it were intentional',

    // ── CONTENT & TOPICS (50) ────────────────────────────────────
    'A sports score or result is mentioned',
    'Weather is covered',
    'A student club is spotlighted',
    'A student is interviewed on camera',
    'A teacher appears on screen',
    'A school event is promoted more than once',
    'A student athlete is named specifically',
    'A charity or fundraiser is mentioned',
    'A student\'s artwork is shown on camera',
    'Academic achievement is highlighted',
    'A schedule change is announced',
    'A performance (play, concert, dance) is covered',
    'A field trip is mentioned',
    'A school spirit segment airs',
    'A "good news" story closes the broadcast',
    'A holiday or observance is mentioned',
    'A cafeteria item is referenced',
    'A teacher recognition segment airs',
    'SAT, ACT, or AP exams are mentioned',
    'A scholarship or student award is announced',
    'College acceptances or senior milestones are featured',
    'A school safety topic is covered',
    'A student election story airs',
    'A STEM or science story airs',
    'An arts story airs',
    'A story features 3+ interview subjects',
    'An interview happens in the hallway',
    'An interview happens in a classroom',
    'An interview happens in a gym or sports facility',
    'A student reads a prepared statement on air',
    'A student photo montage plays',
    'A story involves a competition',
    'A visiting speaker or guest is mentioned',
    'A community service story airs',
    'A pep rally is referenced',
    'Homecoming is mentioned',
    'Prom is mentioned',
    'Graduation is mentioned',
    'A school record is announced',
    'A "this day in history" segment airs',
    'A social media story airs',
    'A mental health or wellness story airs',
    'The school mascot is shown',
    'A behind-the-scenes ENN segment airs',
    'A school anniversary or milestone is highlighted',
    'A food-related story airs',
    'A student group performs on tape',
    'An Eastlake alumni story airs',
    'Career day or future plans are covered',
    'A story directly addresses you as a student',

    // ── EASTLAKE SPECIFIC (50) ───────────────────────────────────
    'The Titan logo appears on screen',
    'Chula Vista is mentioned by name',
    'A home game is referenced',
    '"Go Titans" is said or shown on screen',
    'The school address is mentioned',
    'Room 506 is referenced',
    'The school year appears on screen',
    'An Eastlake teacher is named on screen',
    'The Eastlake campus is shown from outside',
    'The front entrance appears in B-roll',
    'The gym or sports complex is shown',
    'The library or media center is referenced',
    'A student in ENN gear appears on camera',
    'The ENN studio appears in a behind-the-scenes shot',
    'A Titan pride chant or motto is used',
    'The school bell is heard in B-roll',
    'An Eastlake-specific event is covered',
    'A San Diego or South Bay reference is made',
    'A local business is mentioned',
    'An Eastlake alumni achievement is announced',
    '"Eastlake High School" is said in full on screen',
    'A specific Eastlake classroom is shown',
    'An anchor wears blue, white, or gold',
    'A Titan mascot graphic appears',
    'Another local school is mentioned',
    'The football field appears in B-roll',
    'The track or outdoor area is shown',
    'The Eastlake parking lot is in B-roll',
    'A staff member from outside broadcast class appears',
    'A senior is featured or interviewed',
    'A freshman is featured or interviewed',
    'The school\'s social media handle is shown on screen',
    'A student in a graduation cap or gown appears',
    '"Titans" appears in a graphic',
    'A campus mural or artwork appears in B-roll',
    'A counselor or administrator is interviewed',
    'The principal\'s name is mentioned',
    'An AP or honors class is referenced',
    '"Campus" is used three or more times in one story',
    'Eastlake\'s history or founding is referenced',
    'A student in club uniform (band, cheer, etc.) appears',
    'Band, orchestra, or choir is mentioned',
    'A track or cross-country result is announced',
    'A swim or water polo result is mentioned',
    'A volleyball, basketball, or soccer score is given',
    'A wrestling, football, or baseball result is mentioned',
    'The robotics or science club is featured',
    'An ASB or student government story airs',
    'ENN itself is mentioned as a resource',
    'The broadcast airs from an off-campus location',

    // ── META (50) ────────────────────────────────────────────────
    'You spot a camera operator in a reflection',
    'Someone in B-roll notices the camera',
    'Broadcast opens exactly on time',
    'A student waves in the background of B-roll',
    'A crew member is briefly at the edge of frame',
    'A reporter is still setting up when the story begins',
    'The anchor visibly checks the time',
    'Someone walks through the background of a live shot',
    'A camera shadow falls on the subject',
    'A reporter glances at their phone between takes',
    'Teleprompter speed is visibly wrong',
    'An anchor breaks into a smile during a serious story',
    'The broadcast runs shorter than expected',
    'The broadcast runs longer than expected',
    'A production credit at the end is misspelled',
    'The broadcast intro plays again by mistake',
    'You can see the studio lights in a wide shot',
    'The anchor desk has visible props or phones on it',
    'A segment ends and nothing happens for a moment',
    'A crew member laughs audibly off camera',
    'Someone\'s phone rings off camera',
    'A reporter finishes and visibly waits for a cue',
    'An anchor pauses as if seeing their script for the first time',
    'The ENN logo appears more than 5 times in a single broadcast',
    'Two different fonts appear in the same graphic',
    'The theme music is too loud during the intro',
    'A previous story\'s graphic lingers into a new segment',
    'A reporter\'s standup is clearly from a different location',
    'An anchor comments after a reporter\'s piece',
    'An anchor compliments the reporter on air',
    'A story about ENN\'s own equipment or operations airs',
    'End credits are longer than the last story',
    'A story title is funnier than the story itself',
    '"Here at ENN" is said unprompted',
    'The broadcast opens with a rhetorical question',
    'You recognize a classmate in B-roll',
    'You see your locker or classroom in a background shot',
    'An anchor speaks directly to a specific student',
    'A graphic reuses an image from a previous week',
    'A clip is clearly filmed on a phone camera',
    'A story ends with a zoom that doesn\'t quite land',
    'The broadcast tone shifts dramatically between stories',
    'A reporter uses their own hand for scale in a shot',
    'The anchor desk mic stand is the only thing in focus',
    '"Your ENN team" or "your news team" is said',
    'A graphic has a drop shadow that looks retro',
    'The same B-roll clip plays in two different stories',
    'A reporter\'s story runs much longer than the intro suggested',
    'A crew member is visible in a window reflection',
    'You\'re filling out this bingo card while watching — BONUS',

  ],

};
