#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#  ENN Hero Frame Converter
#  Converts 4K PNG sequence (with alpha) → 1920×1080 WebP
#  Then auto-generates ANIMATION/frames.js
#
#  USAGE:
#    1. Drop your PNG frames into  ANIMATION/raw/
#    2. From the repo root, run:   bash ANIMATION/convert.sh
#
#  OPTIONS (edit below if needed):
#    WIDTH / HEIGHT  — output resolution (default 1920×1080)
#    QUALITY         — WebP quality 0–100 (default 92 — near-lossless)
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INPUT_DIR="$SCRIPT_DIR/raw"
OUTPUT_DIR="$SCRIPT_DIR/frames"
FRAMES_JS="$SCRIPT_DIR/frames.js"
WIDTH=1920
HEIGHT=1080
QUALITY=92          # 92 = near-lossless, very fast decode; drop to 85 to halve file sizes

# ── Checks ──────────────────────────────────────────────────────────
echo ""
echo "  ┌─────────────────────────────────────────────┐"
echo "  │   ENN Hero Frame Converter                  │"
echo "  └─────────────────────────────────────────────┘"
echo ""

if ! command -v ffmpeg &>/dev/null; then
  echo "  ✗  FFmpeg not found."
  echo "     Install it with:  brew install ffmpeg"
  echo ""
  exit 1
fi

mapfile -t PNGS < <(ls "$INPUT_DIR"/*.png 2>/dev/null | sort -V)
TOTAL=${#PNGS[@]}

if [ "$TOTAL" -eq 0 ]; then
  echo "  ✗  No PNG files found in ANIMATION/raw/"
  echo "     Drop your exported frames there, then run this script again."
  echo ""
  exit 1
fi

echo "  →  Input:      $INPUT_DIR"
echo "  →  Output:     $OUTPUT_DIR"
echo "  →  Resolution: ${WIDTH}×${HEIGHT}"
echo "  →  Quality:    $QUALITY"
echo "  →  Frames:     $TOTAL"
echo ""

mkdir -p "$OUTPUT_DIR"

# ── Convert ─────────────────────────────────────────────────────────
START_TIME=$SECONDS
i=0
for f in "${PNGS[@]}"; do
  OUT="$OUTPUT_DIR/$(printf 'f%04d' $i).webp"
  ffmpeg -i "$f" \
    -vf "scale=${WIDTH}:${HEIGHT}:flags=lanczos" \
    -c:v libwebp \
    -quality "$QUALITY" \
    -lossless 0 \
    -compression_level 5 \
    "$OUT" -y -loglevel error
  i=$((i + 1))
  # Progress bar
  FILLED=$((i * 40 / TOTAL))
  BAR=$(printf '%0.s█' $(seq 1 $FILLED))$(printf '%0.s░' $(seq 1 $((40 - FILLED))))
  printf "\r  [%s]  %d / %d" "$BAR" "$i" "$TOTAL"
done
echo ""
echo ""

# ── Generate frames.js ──────────────────────────────────────────────
{
  echo "/* ════════════════════════════════════════════════════"
  echo "   AUTO-GENERATED by ANIMATION/convert.sh"
  echo "   $i frames · ${WIDTH}×${HEIGHT} · WebP q${QUALITY}"
  echo "   DO NOT EDIT — re-run convert.sh to regenerate"
  echo "   ════════════════════════════════════════════════════ */"
  echo "var FRAMES = ["
  for j in $(seq 0 $((i - 1))); do
    printf "  'ANIMATION/frames/f%04d.webp',\n" "$j"
  done
  echo "];"
} > "$FRAMES_JS"

# ── Summary ─────────────────────────────────────────────────────────
ELAPSED=$((SECONDS - START_TIME))
SIZE=$(du -sh "$OUTPUT_DIR" | cut -f1)
AVG_KB=$(( $(du -sk "$OUTPUT_DIR" | cut -f1) / i ))

echo "  ✓  $i frames written to ANIMATION/frames/"
echo "  ✓  frames.js updated"
echo "  ✓  Total size:   $SIZE  (~${AVG_KB}KB avg per frame)"
echo "  ✓  Time:         ${ELAPSED}s"
echo ""
echo "  Reload the site — your animation is live."
echo ""
